// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Context;

namespace WebAPI.Migrations
{
    [DbContext(typeof(IMToolContext))]
    [Migration("20200128192537_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Entities.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentDeviceTypeId");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("DeviceId");

                    b.HasIndex("CurrentDeviceTypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("WebAPI.Entities.DeviceType", b =>
                {
                    b.Property<int>("DeviceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.HasKey("DeviceTypeId");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("WebAPI.Entities.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentDeviceTypeId");

                    b.Property<string>("Description");

                    b.HasKey("IncidentId");

                    b.HasIndex("CurrentDeviceTypeId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("WebAPI.Entities.OccurredIncident", b =>
                {
                    b.Property<int>("OccurredIncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentDeviceId");

                    b.Property<int>("CurrentUserId");

                    b.Property<string>("DeviceName");

                    b.Property<string>("IncidentDescription");

                    b.Property<bool>("Solved");

                    b.HasKey("OccurredIncidentId");

                    b.HasIndex("CurrentUserId");

                    b.ToTable("OccurredIncidents");
                });

            modelBuilder.Entity("WebAPI.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPI.Entities.Device", b =>
                {
                    b.HasOne("WebAPI.Entities.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("CurrentDeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebAPI.Entities.Incident", b =>
                {
                    b.HasOne("WebAPI.Entities.DeviceType", "DeviceType")
                        .WithMany("Incidents")
                        .HasForeignKey("CurrentDeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebAPI.Entities.OccurredIncident", b =>
                {
                    b.HasOne("WebAPI.Entities.User", "User")
                        .WithMany("OccurredIncidents")
                        .HasForeignKey("CurrentUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
